### PR TITLE
Added "eCourse" for the showcase page

### PR DESCRIPTION
**Pull request by Ilyas-Codes**
I would love to see my first PocketBase/PocketHost app on the showcase page, also thanks again for helping me out!

### CODE REVIEW

**Comment by Ilyas-Codes** [comment]
I can't afford one lol, will it be better if I use the pockethost.io subdomain? "https://ecourse.pockethost.io/" I can just move my frontend to pockethost.

**Comment by directormac** [comment]
> I can't afford one lol, will it be better if I use the pockethost.io subdomain? "https://ecourse.pockethost.io/" I can just move my frontend to pockethost.

If there are no specific CF thing in your package, you can push the post build through ftp in your pockethost instance in its pb_public if its compiled as front end the end link would look like e-course.pockethost.io if your instance at pcokethose is named e-course

**Comment by Ilyas-Codes** [comment]
Exactly, I'm waiting for Ben to see if he's okay with that.

**Comment by benallfree** [comment]
Hey guys yeah I think that would be a great idea. Ultimately we are looking for production-ready showcases but I think if it’s in a pockethost.io subdomain that’s a special kind of showcase too.

**Comment by Ilyas-Codes** [comment]
@benallfree Hey, I updated the URL of eCourse to the Pockethost subdomain.

**Comment by Ilyas-Codes** [comment]
@Hyperclaw79 Yes, my frontend is written in Svelte. you simply have to copy the contents of the `dist` folder inside the `pb_public` directory of your Pockethost instance using FTP. this is how I did it with FTP and ncftp (if you have homebrew, run this command to get both `brew install inetutils ncftp`). go to the directory where you have `package.json` and run this command: `npm run build` a dist folder will show up with your bundled frontend code, then go to your Pockethost account, turn on 'maintenance mode' and copy the command from the FTP section, run that command and `cd` to "your_instance_name/pb_public" open another terminal tab and run this command: `ncftpput -R -v -u your_pockethost_email -p your_pockethost_password ftp.sfo-1.pockethost.io /your_instance_name/pb_public /file/path/to/dist/*` that will copy the contents of the dist folder from your local system to the Pockethost server. you can do the same thing with FileZilla or some other FTP client.

**Comment by Hyperclaw79** [comment]
@Ilyas-Codes Great! I'll give it a go, thank you.

**Comment by benallfree** [comment]
https://www.npmjs.com/package/ftp-deploy might also be an option. I haven’t tried it.

**Pull request merged**
