### PR TITLE
Added HT Dev Portfolio to the showcase.

### PR DESCRIPTION
**Pull request by Hyperclaw79**

### CODE REVIEW

**Comment by benallfree** [comment]
Do you have an official domain name for this? I'd like to avoid showcasing *.vercel.app

**Comment by Hyperclaw79** [comment]
Oh if is possible to host the entire thing on PocketHost, that would be really good since it will reduce the DB latency.
However, this is a svelte app written in typescript, so it would require a node server to transpile it into JS and start the local server at the edge.
Is something like that possible with Pockethost? I was under the impression that it can only serve static pages.

**Comment by benallfree** [comment]
You’d need to build it using the static adapter

**Comment by Hyperclaw79** [comment]
Unfortunately that would not be possible since my app has a middleman api which cannot be prerendered. It is not SSG project so it would require a running node server I believe.

**Comment by benallfree** [comment]
@Hyperclaw79 I'm going to leave this open because we may achieve nodejs backend support soon. If we do, you'll be able to move your project from Vercel to here and then we can have the showcase :)

**Comment by Hyperclaw79** [comment]
Sounds good!

**Comment by mohaidoss** [comment]
@benallfree  @Hyperclaw79 maybe this can be of interest https://www.duckdns.org/ ? or *.duckdns.org is also a no ^^"

**Comment by benallfree** [comment]
@mohaidoss can you explain how please?

**Comment by mohaidoss** [comment]
> ⚠️ This is supposing that vercel doesn't use shared IPV4 !

DuckDns allows you to create subdomains and associate them to an IPV4/IPV6 address. I'm not sure how vercel works, but if you have the ip address associated with your website you can just link it to a DuckDns sub domain.

image

With the config above, **test-vercel-access.duckdns.org** will resolve to the ip above.

**Comment by Hyperclaw79** [comment]
@mohaidoss I think you missed Ben's point. The goal is not about eliminating Vercel domains per se but having the project itself hosted via Pockethost such that we have a fully qualified pockethost url. In that context, DuckDNS is being just another Vercel.
Ben correct me if I'm wrong but I think we're trying to reflect in that dashboard that the project belongs in the Pockethost ecosystem and that would be hard to achieve if it is being shows as hosted elsewhere.

**Pull request closed without merging**
