### PR TITLE
Title Bug Fix When Refreshing

### PR DESCRIPTION
**Pull request by LuminareHQ**
Fixes a bug caused by the new dynamic title, when it tried to set the title before the global instance stores were fully initialized, causing an error. Fixed by implementing the first attempt after the layout has been mounted, and is subsequently checked and set with an interval that is canceled once the title has been set. Setting the title is then passed off to a reactive declaration.

### CODE REVIEW

**Comment by benallfree** [comment]
Could this be causing #365

**Comment by LuminareHQ** [comment]
Yes, this is the fix for that issue

**Comment by benallfree** [comment]
I think this would be better handled as a reactive guard that simply doesn't render the dependent component until `$instance` has a value.

**Comment by benallfree** [comment]
@brewhousedigital

**Comment by LuminareHQ** [comment]
I was trying that, because it is a head element with different rules block I couldn't get it to work without erroring, but that's most likely just a knowledge gap

**Comment by benallfree** [comment]
Or actually couldn't you just move the `<svelte:head>` inside the `{#if isReady}` and avoid all the rest?

**Comment by LuminareHQ** [comment]
svelte head elements do not work in {#if} blocks

**Comment by benallfree** [comment]
How about

```svelte
<svelte:head>
  <title>{$instance?.subdomain || `Instance`} overview - PocketHost</title>
</svelte:head>
```

or


```svelte
<svelte:head>
  <title>{isReady ? $instance.subdomain : `Instance`} overview - PocketHost</title>
</svelte:head>
```

**Comment by LuminareHQ** [comment]
You are correct on the second option, that works fine, first one was the one I tried and it errored still, the `<svelte:head>
  <title>{isReady ? $instance.subdomain : `Instance`} overview - PocketHost</title>
</svelte:head>` is best option

**Comment by benallfree** [comment]
Thank you!!

**Comment by benallfree** [comment]
@LuminareHQ The fence ``` code blocks need to go on separate lines. 

https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code

**Comment by LuminareHQ** [comment]
Ohhh okay thank you! Teams and Github both use different md syntax i guess lmao

**Pull request merged**
