### PR TITLE
[FRONT] Configuration for CORS Origin

### PR DESCRIPTION
**Pull request by mohaidoss**
Hi, this PR enable PocketHost users to setup CORS origins as PocketBase supports this [functionality](https://github.com/pocketbase/pocketbase/blob/master/cmd/serve.go#L55)

## Frontend/Middleware
From my understanding of the code base this requires to add a column called `corsOrigins` of type string `'example.com,http://app.example.com'`  

## Backend
If you can guide me on which files or directory I should be checking for this, I can do it like the following:

- [ ] a check for the value in column corsOrigins for a given instance
- [ ] add --origins as an argument with the corsOrigins values if corsOrigins is not null or not empty

## Documentation

- [ ] Documentation for the above configuration

### CODE REVIEW

**Comment by benallfree** [comment]
...although, it appears that `--origins='domain1.com,domain2.com'` is what the command line switch wants...

**Comment by benallfree** [comment]
Maybe for this first version we don't validate at all (or minimally as you have) and just tell the users that it is passed straight to pocketbase. What do you think?

**Comment by mohaidoss** [comment]
Agree, or see what the community has to say ?

**Comment by drhuster** [comment]
I was just checking for this in the discord https://discord.com/channels/1128192380500193370/1199828287921328199. I also asked about if this is something I could do with hooks. Gani mentioned I should use `./pocketbase serve --origins=example1.com,example2.com` as the way to set cors. As looking for a host in a hook would
https://github.com/pocketbase/pocketbase/discussions/4391#discussioncomment-8533662

Postman, curls, etc, would still be an issue, but it could at least leverage the browser's built in security features. 

So I would like to see this feature added - if only because it would make a feature of PocketBase accessible.

I am guessing the right solution would involve hooks with a combination of headers/token validation - but that seems way out of scope for this PR

**Comment by mohaidoss** [comment]
@drhuster This is indeed the purpose of this PR, to make the origins configuration of PocketBase accessible in PocketHost.

However there is still the backend (Instance launch with origins if specified) to be done.

I don't mind implementing this, but I need a lead from Ben to know from where to start

**Comment by benallfree** [comment]
I'll probably save this one for after the CLI release (maybe). The backend code base will be easier to navigate at that point. 

To me this is a low priority because nothing is broken, am I wrong?

**Comment by drhuster** [comment]
I just saw that this PR was 2 weeks old and did not want it forgotten. But I totally forgot this was just the front end part; my bad! As for priority, I am sure there are a ton of competing requests. I just wanted to put my voice behind this one, as supporting cors is one piece of the puzzle where a project can limit unauthorized access to pocketbase (not that it protects against all vectors).

**Comment by mohaidoss** [comment]
@benallfree does this feature already exist ?

**Comment by mohaidoss** [comment]
@benallfree then why are we not merging this ?

**Pull request closed without merging**
