### PR TITLE
Dashboard Cleanup

### PR DESCRIPTION
**Pull request by mmgfrcs**
A lot of minor changes to the main Dashboard UI and the Instance Details menu.

Mostly a cleanup to the UI:

- Fix font sizes
- Fix the top Navbar, the logo, the Apps dropdown, and the Avatar
- Fix Maintenance Mode visibility on the Dashboard
- Fix menu mess on Instance Details UI
- Increase Log font size

etc.

### CODE REVIEW

**Comment by benallfree** [comment]
`v0/no-lander` is the branch that the Discord thread is based on. As you can see there are merge conflicts. Please send a PR against that branch.

**Comment by mmgfrcs** [comment]
Well, I'll need to restart from the beginning then :)

**Comment by benallfree** [comment]
Maybe not. I haven't checked the merge conflicts, they might be easy.

**Comment by mmgfrcs** [comment]
Probably, but the `v0/no-lander` branch looks cleaner (with fewer files and things structured differently) so I don't know if resolving the merge conflicts would make it mergeable

**Comment by benallfree** [comment]
Ok well thanks for the thoughtful updates. If you decide to port them to the new branch it would be super helpful. :)

**Pull request closed without merging**
